<?php

namespace ContainerQ3z7wxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SPt2UwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s_Pt2Uw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s_Pt2Uw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gotenberg' => ['privates', 'App\\Service\\Gotenberg', 'getGotenbergService', true],
            'pdfRepository' => ['privates', 'App\\Repository\\PdfRepository', 'getPdfRepositoryService', true],
        ], [
            'entityManager' => '?',
            'gotenberg' => 'App\\Service\\Gotenberg',
            'pdfRepository' => 'App\\Repository\\PdfRepository',
        ]);
    }
}
