<?php

namespace ContainerQ3z7wxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGotenbergService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Gotenberg' shared autowired service.
     *
     * @return \App\Service\Gotenberg
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Gotenberg.php';

        return $container->privates['App\\Service\\Gotenberg'] = new \App\Service\Gotenberg(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
