<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXXN8xUx\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXN8xUx/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXXN8xUx.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXXN8xUx\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXXN8xUx\App_KernelTestDebugContainer([
    'container.build_hash' => 'XXN8xUx',
    'container.build_id' => '45c01eb6',
    'container.build_time' => 1707204011,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXN8xUx');
