<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ3z7wxi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ3z7wxi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ3z7wxi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ3z7wxi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ3z7wxi\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q3z7wxi',
    'container.build_id' => '8991471f',
    'container.build_time' => 1708598046,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ3z7wxi');
