name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        port: 2200  
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www
          if [ -d "pdf/.git" ]; then
            cd pdf
            git pull origin main
          else
            git clone git@github.com:pjoron/SymfonyS6.git testgithub
            cd testgithub
          fi
          composer install
          npm install
          sudo npm run build
